apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels: 
    app: wordpress
  namespace: wordpress
spec:
  type: Nodeport
  selector:
    app: wordpress
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 30008
      
