apiVersion: v1
kind: Service
metadata:
  name: wp_mysql
  labels: 
    name: wordpress
  namespace: wordpress
spec:
  type: ClusterIP
  selector:
    app: wordpress
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
