apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql
  labels:
    app: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: WORDPRESS_DB_USER
          value: toto
        - name: WORDPRESS_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wp-mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress_secret
              key: mysql_password
        - name: MYSQL_ROOT_PASSWORD
          valueForm:
            secretKeyRef:
              name: wordpress_secret
              key: mysql_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql_persistent_storage
          mountPath: /var/lib/mysql
      volumes:  
      - name: mysql-persistent-storage
        hostPath:
          path: /data/mysql
